const prefix = 'DI/CC/VOTER/';

export const GET_NEW_IMAGE_ABORTED = `${prefix}GET_NEW_IMAGE_ABORTED`;
export const GET_NEW_IMAGE_FAILURE = `${prefix}GET_NEW_IMAGE_FAILURE`;
export const GET_NEW_IMAGE_PENDING = `${prefix}GET_NEW_IMAGE_PENDING`;
export const GET_NEW_IMAGE_SUCCESS = `${prefix}GET_NEW_IMAGE_SUCCESS`;

export const SCORE_IMAGE_ABORTED = `${prefix}SCORE_IMAGE_ABORTED`;
export const SCORE_IMAGE_FAILURE = `${prefix}SCORE_IMAGE_FAILURE`;
export const SCORE_IMAGE_PENDING = `${prefix}SCORE_IMAGE_PENDING`;
export const SCORE_IMAGE_SUCCESS = `${prefix}SCORE_IMAGE_SUCCESS`;

export const TOGGLE_IMAGE_FAVORITE_ABORTED = `${prefix}TOGGLE_IMAGE_FAVORITE_ABORTED`;
export const TOGGLE_IMAGE_FAVORITE_FAILURE = `${prefix}TOGGLE_IMAGE_FAVORITE_FAILURE`;
export const TOGGLE_IMAGE_FAVORITE_PENDING = `${prefix}TOGGLE_IMAGE_FAVORITE_PENDING`;
export const TOGGLE_IMAGE_FAVORITE_SUCCESS = `${prefix}TOGGLE_IMAGE_FAVORITE_SUCCESS`;
