const prefix = 'APP/MODULE/STASH/';

export const FETCH_FAVORITE_IMAGES_ABORTED = `${prefix}FETCH_FAVORITE_IMAGES_ABORTED`;
export const FETCH_FAVORITE_IMAGES_FAILURE = `${prefix}FETCH_FAVORITE_IMAGES_FAILURE`;
export const FETCH_FAVORITE_IMAGES_PENDING = `${prefix}FETCH_FAVORITE_IMAGES_PENDING`;
export const FETCH_FAVORITE_IMAGES_SUCCESS = `${prefix}FETCH_FAVORITE_IMAGES_SUCCESS`;

export const FETCH_SCORED_IMAGES_ABORTED = `${prefix}FETCH_SCORED_IMAGES_ABORTED`;
export const FETCH_SCORED_IMAGES_FAILURE = `${prefix}FETCH_SCORED_IMAGES_FAILURE`;
export const FETCH_SCORED_IMAGES_PENDING = `${prefix}FETCH_SCORED_IMAGES_PENDING`;
export const FETCH_SCORED_IMAGES_SUCCESS = `${prefix}FETCH_SCORED_IMAGES_SUCCESS`;

export const SET_VISIBILITY_FILTER = `${prefix}SET_VISIBILITY_FILTER`;
export const VISIBILITY_FILTER_ALL = `${prefix}VISIBILITY_FILTER_ALL`;
export const VISIBILITY_FILTER_FAVORITES = `${prefix}VISIBILITY_FILTER_FAVORITES`;
export const VISIBILITY_FILTER_SCORED = `${prefix}VISIBILITY_FILTER_SCORED`;
